--- # Livenessprobe example for HTTP endpoint
apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-example
  labels:
    name: liveness-probe-app
    app: my-go-server
spec:
  containers:
    - name: liveness-probe-pod
      image: samarthya/epserver:2.0
      env:
        - name: SERVERPORT
          value: "9090"
      resources:
        limits:
          memory: "250Mi"
          cpu: "2000m"
      livenessProbe:
        httpGet:
          path: /health
          port: 9090
        initialDelaySeconds: 5
        periodSeconds: 3
      ports:
        - containerPort: 9090
