apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: my-server
  policyTypes:
    - Ingress
  ingress:
    - to:
      ports:
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 8090
