{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "epserver.serviceAccountName" . }}
  labels:
    {{- include "epserver.labels" . | nindent 4 }}
    environment: {{ .Values.environment | default "development" | quote }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
